version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
  backend:
    build: .
    container_name: backend
    restart: on-failure
    depends_on:
      - mongodb
    expose:
      - 8080
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
volumes:
  mongodb: